### ISSUE TITLE
More robust multi-output recipe?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/strawberry-graphql-feedstock#18]
### Comment:

`strawberry-graphql` has a _huge_ stack of relatively opinionated extras, with version constraints. 

It would be ideal if this was a multi-output repo which separated out the core package, and then each of the extras as outputs, along with some way to keep them in check when things change upstream.

**Comment by thewchan** [comment]
@bollwyvl I was recently added as a maintainer as the previous maintainer seems to be idled for a bit. Any help for a plan to convert this to multi output is super welcomed!

**Comment by bollwyvl** [comment]
Cheers: #19 is up, and employs a (semi-)proven approach to "big undeclared extras" packages which should hopefully be mostly automated. When a new extra appears (or a dep changes), it should be relatively easy to update, but may require a little local intervention, especially if the template has to change.

**Comment by bollwyvl** [comment]
#19 has been working pretty well, and has caught a few small changes. Probably can close now.
